services:
  postgres:
    image: postgres:16-alpine
    container_name: youtube-research-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - youtube-research-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: youtube-research-ollama
    ports:
      - "${OLLAMA_PORT}:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - youtube-research-network
    environment:
      OLLAMA_HOST: 0.0.0.0:11434

  spring-boot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: youtube-research-api
    ports:
      - "${SPRING_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      OLLAMA_BASE_URL: http://host.docker.internal:1234
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - youtube-research-network

  frontend:
    build:
      context: ./frontend/youtube-research-ui
      dockerfile: Dockerfile
    container_name: youtube-research-frontend
    ports:
      - "80:80"
    depends_on:
      - spring-boot-app
    networks:
      - youtube-research-network



volumes:
  postgres_data:
  ollama_data:

networks:
  youtube-research-network:
    driver: bridge